[package]
name = "rust_ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.30.0"
polars-core = "0.30.0"
rustfmt = "0.10.0"
smartcore = "0.2.0"
