name: Rust CI
on: [push]
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        run: cargo check
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - run: rustup component add rustfmt clippy

      - name: run rustfmt
        run: cargo fmt --all -- --check

      - name: run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  
  test:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: run test
      - run: cargo test


  