name: Rust CI
on: [push]
jobs:
  build_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/create_cargo_cache
      - name: build
        run: cargo build
  
  lint:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt clippy
      - name: run rustfmt
        run: cargo fmt --all -- --check

      - name: run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  
  test:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: run test
      - run: cargo test


  